// atomic 0
try {
	x10.runtime.LoadMonitored.blocked(x10.runtime.Sampling.CAUSE_ATOMIC, 0);
	synchronized (x10.lang.Runtime.here()) {
  	    x10.runtime.LoadMonitored.unblocked(x10.runtime.Sampling.CAUSE_ATOMIC, 0);
	    x10.runtime.Sampling.SINGLETON.signalEvent(x10.runtime.Sampling.EVENT_ID_ATOMIC_ENTRY);
		try {        
			#0
			x10.lang.Runtime.here().notifyAll();
		} catch (Throwable e) {
  			e.printStackTrace();
  			x10.lang.Runtime.runtime.java.log(java.util.logging.Level.SEVERE, "Unexpected exception during atomic.", e);
	  		throw new RuntimeException(e);
	  	}
	}
} finally {
    x10.runtime.Sampling.SINGLETON.signalEvent(x10.runtime.Sampling.EVENT_ID_ATOMIC_EXIT);
}
