// atomic 0
synchronized (x10.lang.Runtime.here()) {
	try {
		#0
		x10.lang.Runtime.here().notifyAll();
	} catch (Throwable e) {
  		e.printStackTrace();
  		x10.lang.Runtime.getRuntime().java.log(java.util.logging.Level.SEVERE, "Unexpected exception during atomic.", e);
  		throw new RuntimeException(e);
  	}
}