// SYNOPSIS: await (#0) #1=unique_id

{
	synchronized (x10.lang.Runtime.here()) {
		try {
			while (!(#0)) {
				x10.lang.Runtime.here().wait();
			}
		} catch (Throwable tmp#1) {
			tmp#1.printStackTrace();
			x10.lang.Runtime.runtime.javaRuntime.log(java.util.logging.Level.SEVERE,
					"Unexpected exception during conditional atomic.", tmp#1);
			throw new RuntimeException(tmp#1);
		} finally {
			x10.lang.Runtime.here().notifyAll();
		}
	}
}

